//import { Group, Users, Chore } from '../models';

const choreData = [
    {
        choreName: 'Vacuuming',
        choreBody: '',
        createdAt: 'Sept 30, 2022',
        username: 'Espeon',
        assignedTo: '',
        status: '',
        dueDate: '',
    },
    {
        choreName: 'Take out the trash',
        choreBody: '',
        createdAt: 'Sept 30, 2022',
        username: 'Vaporeon',
        assignedTo: '',
        status: '',
        dueDate: '',
    },
    {
        choreName: 'Clean bathroom',
        choreBody:
            'take out the trash, clean the toilet, clean the mirror, refill the soap',
        createdAt: 'August 27, 2022',
        username: 'Espeon',
        assignedTo: '',
        status: '',
        dueDate: '',
    },
    {
        choreName: 'Wash Dishes',
        choreBody: '',
        createdAt: 'August 27, 2022',
        username: 'Vaporeon',
        assignedTo: '',
        status: '',
        dueDate: '',
    },
    {
        choreName: 'Deep Clean fridge',
        choreBody:
            'removed expired food, throw away old leftovers, wipe down stains',
        createdAt: 'Sept 30, 2022',
        username: 'Flareon',
        assignedTo: '',
        status: '',
        dueDate: '',
    },
    {
        choreName: 'House Laundry',
        choreBody: '',
        createdAt: 'August 27, 2022',
        username: 'Flareon',
        assignedTo: '',
        status: '',
        dueDate: '',
    },
    {
        choreName: 'Cleaning Windows',
        choreBody: '',
        createdAt: 'Oct 3, 2022',
        username: 'Gardevoir',
        assignedTo: '',
        status: '',
        dueDate: '',
    },
    {
        choreName: 'Water Plants',
        choreBody: '',
        createdAt: 'Oct 3, 2022',
        username: 'Gardevoir',
        assignedTo: '',
        status: '',
        dueDate: '',
    },
];
